AllCops:
  TargetRubyVersion: 2.7

Documentation:
    Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

RSpec/VerifiedDoubles:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 4

require: rubocop-rspec
