sudo: false
cache: bundler
language: ruby
rvm:
  - 2.6.3
before_install:
  - gem update --remote bundler
  - sudo apt-get install build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libsndfile-dev libmpg123-dev libgmp-dev
script:
  - bundle exec rspec
  - bundle exec rubocop
