interface:
  map_size: 1024
  sidebar_width: 400
  viewport_size: 256
  starting_point:
    x: 0
    y: 0
world:
  tile_count: 256
  actors:
    count: 10
    starting_point:
      x: 35
      y: 35
  island: false
  octaves: 3
  seed: 10
